apiVersion: v1
kind: Service
metadata:
  name: gateway-websocket
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "30"
spec:
  selector:
    app: gateway-websocket
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
