---
- name: Deploy ChatApp Services
  hosts: all
  become: yes
  tasks:
    - name: Get Terraform outputs
      command: terraform -chdir=../../deploy/terraform output -json
      register: tf_outputs

    - name: Set kubeconfig for EKS
      shell: |
        aws eks update-kubeconfig --region {{ lookup('env', 'AWS_REGION') | default('us-east-1') }} --name {{ lookup('env', 'EKS_CLUSTER_NAME') }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

    - name: Deploy gateway-websocket with Helm
      shell: |
        helm upgrade --install gateway-websocket ../../deploy/helm/gateway-websocket

    - name: Deploy chat-message-service with Helm
      shell: |
        helm upgrade --install chat-message-service ../../deploy/helm/chat-message-service

    - name: Apply ServiceAccount manifest
      shell: |
        kubectl apply -f ../../k8s/serviceaccount-chatapp.yaml
