apiVersion: v1
kind: Service
metadata:
  name: chat-message-service
spec:
  selector:
    app: chat-message-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
