name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Backend: Test & Lint
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Run Go tests (gateway-websocket)
        run: |
          cd services/gateway-websocket
          go test ./...
      - name: Run Go tests (chat-message-service)
        run: |
          cd services/chat-message-service
          go test ./...

      # Frontend: Test & Lint
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: Install frontend dependencies
        run: |
          cd chatapp-frontend
          rm -rf node_modules bun.lock package-lock.json
          npm install
      # - name: Lint frontend
      #   run: |
      #     cd chatapp-frontend
      #     npm run lint
      # (Add frontend tests here if/when available)
      # Build Docker images and push to ECR
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and push gateway-websocket image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/chatapp-gateway-websocket:latest ./services/gateway-websocket
          docker push ${{ steps.login-ecr.outputs.registry }}/chatapp-gateway-websocket:latest
      - name: Build and push chat-message-service image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/chatapp-chat-message-service:latest ./services/chat-message-service
          docker push ${{ steps.login-ecr.outputs.registry }}/chatapp-chat-message-service:latest

      # Inject environment variables from GitHub Secrets and build frontend static site
      - name: Create .env file for frontend
        run: |
          echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}" > chatapp-frontend/.env
          echo "VITE_CHAT_SERVICE_URL=${{ secrets.VITE_CHAT_SERVICE_URL }}" >> chatapp-frontend/.env
      - name: Build frontend static site
        run: |
          cd chatapp-frontend
          npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./chatapp-frontend/dist
          publish_branch: gh-pages
      # Terraform step
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform -chdir=deploy/terraform init
      - name: Terraform Plan
        run: terraform -chdir=deploy/terraform plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform -chdir=deploy/terraform apply -auto-approve
  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Set up Helm
        uses: azure/setup-helm@v3
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}
      - name: Deploy with Helm
        run: |
          helm upgrade --install gateway-websocket ./deploy/helm/gateway-websocket
          helm upgrade --install chat-message-service ./deploy/helm/chat-message-service
      - name: Apply Ingress and ServiceAccount
        run: |
          kubectl apply -f k8s/serviceaccount-chatapp.yaml
